[project]
name = "misc-api"
version = "0.1.0"
description = "A collection of various apis"
requires-python = ">=3.11"
dependencies = [
    "flask",
    "gunicorn",
    "dashscope",
]

[tool.uv]
dev-dependencies = []
